<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Perfil', 'doctrine');

/**
 * BasePerfil
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property timestamp $fecha_creacion
 * @property Doctrine_Collection $PerfilCategoriaTicket
 * @property Doctrine_Collection $Usuario
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getNombre()                Returns the current record's "nombre" value
 * @method timestamp           getFechaCreacion()         Returns the current record's "fecha_creacion" value
 * @method Doctrine_Collection getPerfilCategoriaTicket() Returns the current record's "PerfilCategoriaTicket" collection
 * @method Doctrine_Collection getUsuario()               Returns the current record's "Usuario" collection
 * @method Perfil              setId()                    Sets the current record's "id" value
 * @method Perfil              setNombre()                Sets the current record's "nombre" value
 * @method Perfil              setFechaCreacion()         Sets the current record's "fecha_creacion" value
 * @method Perfil              setPerfilCategoriaTicket() Sets the current record's "PerfilCategoriaTicket" collection
 * @method Perfil              setUsuario()               Sets the current record's "Usuario" collection
 * 
 * @package    clasupport
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerfil extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('perfil');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('fecha_creacion', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PerfilCategoriaTicket', array(
             'local' => 'id',
             'foreign' => 'perfil_id'));

        $this->hasMany('Usuario', array(
             'local' => 'id',
             'foreign' => 'perfil_id'));
    }
}