<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PerfilCategoriaTicket', 'doctrine');

/**
 * BasePerfilCategoriaTicket
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $perfil_id
 * @property integer $categoria_ticket_id
 * @property Perfil $Perfil
 * @property CategoriaTicket $CategoriaTicket
 * 
 * @method integer               getPerfilId()            Returns the current record's "perfil_id" value
 * @method integer               getCategoriaTicketId()   Returns the current record's "categoria_ticket_id" value
 * @method Perfil                getPerfil()              Returns the current record's "Perfil" value
 * @method CategoriaTicket       getCategoriaTicket()     Returns the current record's "CategoriaTicket" value
 * @method PerfilCategoriaTicket setPerfilId()            Sets the current record's "perfil_id" value
 * @method PerfilCategoriaTicket setCategoriaTicketId()   Sets the current record's "categoria_ticket_id" value
 * @method PerfilCategoriaTicket setPerfil()              Sets the current record's "Perfil" value
 * @method PerfilCategoriaTicket setCategoriaTicket()     Sets the current record's "CategoriaTicket" value
 * 
 * @package    clasupport
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePerfilCategoriaTicket extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('perfil_categoria_ticket');
        $this->hasColumn('perfil_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('categoria_ticket_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Perfil', array(
             'local' => 'perfil_id',
             'foreign' => 'id'));

        $this->hasOne('CategoriaTicket', array(
             'local' => 'categoria_ticket_id',
             'foreign' => 'id'));
    }
}