<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Curso', 'doctrine');

/**
 * BaseCurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $nombre_corto
 * @property string $dia
 * @property time $horario
 * @property Doctrine_Collection $UsuarioCurso
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getNombre()       Returns the current record's "nombre" value
 * @method string              getNombreCorto()  Returns the current record's "nombre_corto" value
 * @method string              getDia()          Returns the current record's "dia" value
 * @method time                getHorario()      Returns the current record's "horario" value
 * @method Doctrine_Collection getUsuarioCurso() Returns the current record's "UsuarioCurso" collection
 * @method Curso               setId()           Sets the current record's "id" value
 * @method Curso               setNombre()       Sets the current record's "nombre" value
 * @method Curso               setNombreCorto()  Sets the current record's "nombre_corto" value
 * @method Curso               setDia()          Sets the current record's "dia" value
 * @method Curso               setHorario()      Sets the current record's "horario" value
 * @method Curso               setUsuarioCurso() Sets the current record's "UsuarioCurso" collection
 * 
 * @package    clasupport
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('curso');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('nombre_corto', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('dia', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('horario', 'time', 25, array(
             'type' => 'time',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UsuarioCurso', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));
    }
}