<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Nota', 'doctrine');

/**
 * BaseNota
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $fecha_alta
 * @property string $texto
 * @property integer $ticket_id
 * @property Ticket $Ticket
 * 
 * @method integer   getId()         Returns the current record's "id" value
 * @method timestamp getFechaAlta()  Returns the current record's "fecha_alta" value
 * @method string    getTexto()      Returns the current record's "texto" value
 * @method integer   getTicketId()   Returns the current record's "ticket_id" value
 * @method Ticket    getTicket()     Returns the current record's "Ticket" value
 * @method Nota      setId()         Sets the current record's "id" value
 * @method Nota      setFechaAlta()  Sets the current record's "fecha_alta" value
 * @method Nota      setTexto()      Sets the current record's "texto" value
 * @method Nota      setTicketId()   Sets the current record's "ticket_id" value
 * @method Nota      setTicket()     Sets the current record's "Ticket" value
 * 
 * @package    clasupport
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNota extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nota');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha_alta', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('texto', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('ticket_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Ticket', array(
             'local' => 'ticket_id',
             'foreign' => 'id'));
    }
}