<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UsuarioCurso', 'doctrine');

/**
 * BaseUsuarioCurso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $curso_id
 * @property integer $usuario_id
 * @property Usuario $Usuario
 * @property Curso $Curso
 * 
 * @method integer      getCursoId()    Returns the current record's "curso_id" value
 * @method integer      getUsuarioId()  Returns the current record's "usuario_id" value
 * @method Usuario      getUsuario()    Returns the current record's "Usuario" value
 * @method Curso        getCurso()      Returns the current record's "Curso" value
 * @method UsuarioCurso setCursoId()    Sets the current record's "curso_id" value
 * @method UsuarioCurso setUsuarioId()  Sets the current record's "usuario_id" value
 * @method UsuarioCurso setUsuario()    Sets the current record's "Usuario" value
 * @method UsuarioCurso setCurso()      Sets the current record's "Curso" value
 * 
 * @package    clasupport
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsuarioCurso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario_curso');
        $this->hasColumn('curso_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'curso_id',
             'foreign' => 'id'));

        $this->hasOne('Curso', array(
             'local' => 'usuario_id',
             'foreign' => 'id'));
    }
}