<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EstadoUsuario', 'doctrine');

/**
 * BaseEstadoUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $Usuario
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getNombre()  Returns the current record's "nombre" value
 * @method Doctrine_Collection getUsuario() Returns the current record's "Usuario" collection
 * @method EstadoUsuario       setId()      Sets the current record's "id" value
 * @method EstadoUsuario       setNombre()  Sets the current record's "nombre" value
 * @method EstadoUsuario       setUsuario() Sets the current record's "Usuario" collection
 * 
 * @package    clasupport
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstadoUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estado_usuario');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Usuario', array(
             'local' => 'id',
             'foreign' => 'estado_usuario_id'));
    }
}