<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CategoriaTicket', 'doctrine');

/**
 * BaseCategoriaTicket
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $descripcion
 * @property Doctrine_Collection $PerfilCategoriaTicket
 * @property Doctrine_Collection $Ticket
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getNombre()                Returns the current record's "nombre" value
 * @method string              getDescripcion()           Returns the current record's "descripcion" value
 * @method Doctrine_Collection getPerfilCategoriaTicket() Returns the current record's "PerfilCategoriaTicket" collection
 * @method Doctrine_Collection getTicket()                Returns the current record's "Ticket" collection
 * @method CategoriaTicket     setId()                    Sets the current record's "id" value
 * @method CategoriaTicket     setNombre()                Sets the current record's "nombre" value
 * @method CategoriaTicket     setDescripcion()           Sets the current record's "descripcion" value
 * @method CategoriaTicket     setPerfilCategoriaTicket() Sets the current record's "PerfilCategoriaTicket" collection
 * @method CategoriaTicket     setTicket()                Sets the current record's "Ticket" collection
 * 
 * @package    clasupport
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoriaTicket extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categoria_ticket');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('descripcion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PerfilCategoriaTicket', array(
             'local' => 'id',
             'foreign' => 'categoria_ticket_id'));

        $this->hasMany('Ticket', array(
             'local' => 'id',
             'foreign' => 'categoria_ticket_id'));
    }
}