<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/09/28 01:46:22

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=clasupport',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
