<?php

/**
 * CategoriaTicketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriaTicketTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoriaTicketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoriaTicket');
    }
}