<?php

/**
 * EstadoTicketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoTicketTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadoTicketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadoTicket');
    }
}