<?php

/**
 * EstadoUsuarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EstadoUsuarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EstadoUsuarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EstadoUsuario');
    }
}