<?php

/**
 * PerfilCategoriaTicketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PerfilCategoriaTicketTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PerfilCategoriaTicketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PerfilCategoriaTicket');
    }
}