# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        CLA Support
    description:  soporte para alumnos de cla linux institute
    keywords:     soporte, cla, linux, project
    language:     es
    robots:       index, follow

  stylesheets:    [bootstrap.css]

  javascripts:    [jquery.js, bootstrap.js]

  has_layout:     true
  layout:         layout
