<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/10/05 01:17:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=clasupport;host=127.0.0.1',
  'username' => 'clasupport',
  'password' => 'clasupport',
  'name' => 'doctrine',
)),);
